name: agung_auth
description: "A TOTP Authenticator app with sync capability"
publish_to: 'none'
version: 1.0.5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  crypto: ^3.0.3
  base32: ^2.1.3
  mobile_scanner: ^7.0.0
  shared_preferences: ^2.5.3
  local_auth: ^2.3.0
  material_symbols_icons: ^4.2815.0
  url_launcher: ^6.3.1
  dynamic_color: ^1.7.0
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.3
  otp: ^3.1.4
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  otpauth_migration: ^0.0.7
  flutter_autoupdate: ^1.0.0
  pub_semver: ^2.2.0
  package_info_plus: ^8.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/agung_auth.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/agung_auth.png
