// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS4SBVhyiRjC4z5udgz9vKPZIZ5Y-QqU8',
    appId: '1:324982137742:web:07c40b4a6dd299541ffadf',
    messagingSenderId: '324982137742',
    projectId: 'agung-dev-project',
    authDomain: 'agung-dev-project.firebaseapp.com',
    databaseURL: 'https://agung-dev-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agung-dev-project.firebasestorage.app',
    measurementId: 'G-6HGCP88TVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd9Cng0eir-2SOa9WPgYvRa4bEhZAv96g',
    appId: '1:324982137742:android:bd381517d1c756b21ffadf',
    messagingSenderId: '324982137742',
    projectId: 'agung-dev-project',
    databaseURL: 'https://agung-dev-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agung-dev-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDabM-Mx5ljrx6Ph5nYIrrC8fgJjtSHQRo',
    appId: '1:324982137742:ios:c2459413274e89571ffadf',
    messagingSenderId: '324982137742',
    projectId: 'agung-dev-project',
    databaseURL: 'https://agung-dev-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agung-dev-project.firebasestorage.app',
    iosClientId: '324982137742-tsns52qm3a03gjoa52uvf148tticv0h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.agungAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDabM-Mx5ljrx6Ph5nYIrrC8fgJjtSHQRo',
    appId: '1:324982137742:ios:c2459413274e89571ffadf',
    messagingSenderId: '324982137742',
    projectId: 'agung-dev-project',
    databaseURL: 'https://agung-dev-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agung-dev-project.firebasestorage.app',
    iosClientId: '324982137742-tsns52qm3a03gjoa52uvf148tticv0h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.agungAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS4SBVhyiRjC4z5udgz9vKPZIZ5Y-QqU8',
    appId: '1:324982137742:web:12e4bca9a32920c31ffadf',
    messagingSenderId: '324982137742',
    projectId: 'agung-dev-project',
    authDomain: 'agung-dev-project.firebaseapp.com',
    databaseURL: 'https://agung-dev-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agung-dev-project.firebasestorage.app',
    measurementId: 'G-GL7MQKC13C',
  );
}
